In [43]:
# download data from "https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.estv.admin.ch%2Fdam%2Fde%2Fsd-web%2Fwum7OKVNOOwl%2Fstatistik-dbst-np-gden-2022-normalfall.xlsx&wdOrigin=BROWSELINK"
# statistik-dbst-np-gden-2022-normalfall

In [44]:
import pandas as pd
import numpy as np

In [45]:
#extract excel data

income_file = "data/statistik-dbst-np-gden-2022-normalfall.xlsx"

excel_file = pd.ExcelFile(income_file)

# The workbook contains one sheet for every year from 2022.
print(excel_file.sheet_names)

['Erläuterungen', 'Explication', '511', '512', '513', '521', '522', '523', '524']

In [67]:
# Sheet 522 is income
# Sheet 511 is number of taxpayers

# clean 511 first
taxpayers_preview = pd.read_excel(
    excel_file,
    sheet_name="511",
    header=None,
    nrows=20
)

taxpayers_preview.head(20)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"Steuerperiode: 2022, Steuerpflichtige mit und ...",NaN,NaN,NaN,Anzahl steuerpflichtige Personen / Nombre de c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"- Zahlen werden nur ausgewiesen, falls Datensc...",NaN,NaN,NaN,Klassen des reinen Einkommens in CHF / Classes...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kanton ID,Kanton / Canton,Gemeinde ID,Gemeinde / Commune,0,1 - 30'000,30'001 - 40'000,40'001 - 50'000,50'001 - 75'000,75'001 - 100'000,100'001 - 200'000,200'001 - 500'000,500'001 - 1'000'000,1'000'001 - u.m./et plus,Total / Totale
3,1,Zürich,1,Aeugst am Albis,-,222,73,78,179,139,284,96,12,-,1087
4,NaN,NaN,2,Affoltern am Albis,-,1540,540,725,1692,982,1126,210,11,-,6829
5,NaN,NaN,3,Bonstetten,-,541,161,206,568,488,754,188,7,-,2914
6,NaN,NaN,4,Hausen am Albis,4,429,132,213,440,285,457,117,6,-,2086
7,NaN,NaN,5,Hedingen,-,402,126,160,425,322,473,135,17,-,2064
8,NaN,NaN,6,Kappel am Albis,-,122,37,57,136,109,158,41,7,-,668
9,NaN,NaN,7,Knonau,-,226,84,97,264,168,283,64,-,-,1191
10,NaN,NaN,8,Maschwanden,-,71,28,37,79,54,73,8,-,-,351
11,NaN,NaN,9,Mettmenstetten,-,555,189,256,624,436,690,163,13,5,2933
12,NaN,NaN,10,Obfelden,5,596,220,284,690,448,692,94,9,-,3039
13,NaN,NaN,11,Ottenbach,-,307,112,115,327,230,368,77,5,-,1542
14,NaN,NaN,12,Rifferswil,-,109,35,47,109,77,165,40,-,-,586
15,NaN,NaN,13,Stallikon,-,361,105,127,359,277,545,149,15,-,1939
16,NaN,NaN,14,Wettswil am Albis,-,480,151,152,455,335,722,295,27,7,2627
17,NaN,NaN,21,Adlikon,-,62,22,34,90,66,80,10,-,-,365
18,NaN,NaN,22,Benken (ZH),-,104,37,59,104,64,85,16,-,-,474
19,NaN,NaN,23,Berg am Irchel,-,56,24,24,82,65,76,10,-,-,342

In [68]:
# load and skip row
taxpayers_df = pd.read_excel(
    excel_file,
    sheet_name="511",
    skiprows=2,
    header=0
)

taxpayers_df.head()

,Kanton ID,Kanton / Canton,Gemeinde ID,Gemeinde / Commune,0,1 - 30'000,30'001 - 40'000,40'001 - 50'000,50'001 - 75'000,75'001 - 100'000,100'001 - 200'000,200'001 - 500'000,500'001 - 1'000'000,1'000'001 - u.m./et plus,Total / Totale
0,1.0,Zürich,1,Aeugst am Albis,-,222,73,78,179,139,284,96,12,-,1087
1,NaN,NaN,2,Affoltern am Albis,-,1540,540,725,1692,982,1126,210,11,-,6829
2,NaN,NaN,3,Bonstetten,-,541,161,206,568,488,754,188,7,-,2914
3,NaN,NaN,4,Hausen am Albis,4,429,132,213,440,285,457,117,6,-,2086
4,NaN,NaN,5,Hedingen,-,402,126,160,425,322,473,135,17,-,2064

In [69]:
taxpayers_df.tail(20)

,Kanton ID,Kanton / Canton,Gemeinde ID,Gemeinde / Commune,0,1 - 30'000,30'001 - 40'000,40'001 - 50'000,50'001 - 75'000,75'001 - 100'000,100'001 - 200'000,200'001 - 500'000,500'001 - 1'000'000,1'000'001 - u.m./et plus,Total / Totale
2155,NaN,NaN,6775,Bonfol,18,111,43,58,76,55,29,-,-,-,392
2156,NaN,NaN,6778,Bure,18,95,31,31,84,54,57,6,-,-,377
2157,NaN,NaN,6781,Coeuve,26,80,37,45,80,58,76,-,-,-,404
2158,NaN,NaN,6782,Cornol,27,151,72,94,138,62,76,6,-,-,627
2159,NaN,NaN,6783,Courchavon,11,44,12,19,35,24,26,-,-,-,175
2160,NaN,NaN,6784,Courgenay,74,396,173,205,327,171,180,11,-,-,1538
2161,NaN,NaN,6785,Courtedoux,19,110,56,59,89,53,64,7,-,-,459
2162,NaN,NaN,6787,Damphreux,5,40,9,16,20,17,8,-,-,-,116
2163,NaN,NaN,6789,Fahy,5,64,21,28,32,20,28,-,-,-,198
2164,NaN,NaN,6790,Fontenais,43,283,86,130,217,105,137,18,-,-,1019
2165,NaN,NaN,6792,Grandfontaine,12,59,27,34,40,28,24,-,-,-,227
2166,NaN,NaN,6793,Lugnez,5,36,8,13,14,8,18,-,-,-,102
2167,NaN,NaN,6800,Porrentruy,226,1262,411,492,759,376,428,66,4,-,4026
2168,NaN,NaN,6806,Vendlincourt,8,109,36,41,76,33,33,5,-,-,341
2169,NaN,NaN,6807,Basse-Allaine,31,218,91,80,126,100,81,7,-,-,734
2170,NaN,NaN,6808,Clos du Doubs,24,229,81,116,175,82,72,7,-,-,786
2171,NaN,NaN,6809,Haute-Ajoie,27,173,80,93,158,77,69,-,-,-,680
2172,NaN,NaN,6810,La Baroche,31,222,80,91,162,69,62,5,-,-,722
2173,26.0,Jura,10000,Total / Totale,2052,11974,4385,5417,9722,5061,5354,501,33,9,44508
2174,27.0,Schweiz / Suisse / Svizzera / Svizra,10000,Total / Totale,89494,1116206,399948,512639,1116430,654116,760491,132688,12535,3916,4798463

In [70]:
# Check null
taxpayers_df.isna().sum()

Kanton ID                   2122
Kanton / Canton             2122
Gemeinde ID                    0
Gemeinde / Commune             0
0                              0
1 - 30'000                     0
30'001 - 40'000                0
40'001 - 50'000                0
50'001 - 75'000                0
75'001 - 100'000               0
100'001 - 200'000              0
200'001 - 500'000              0
500'001 - 1'000'000            0
1'000'001 - u.m./et plus       0
Total / Totale                 0
dtype: int64

In [71]:
# first fill-forword Kanton ID and Kanton/Canton

taxpayers_df["Kanton ID"] = taxpayers_df["Kanton ID"].ffill()
taxpayers_df["Kanton / Canton"] = taxpayers_df["Kanton / Canton"].ffill()

# check null value again
taxpayers_df.isna().sum()

Kanton ID                   0
Kanton / Canton             0
Gemeinde ID                 0
Gemeinde / Commune          0
0                           0
1 - 30'000                  0
30'001 - 40'000             0
40'001 - 50'000             0
50'001 - 75'000             0
75'001 - 100'000            0
100'001 - 200'000           0
200'001 - 500'000           0
500'001 - 1'000'000         0
1'000'001 - u.m./et plus    0
Total / Totale              0
dtype: int64

In [72]:
taxpayers_df.head()

,Kanton ID,Kanton / Canton,Gemeinde ID,Gemeinde / Commune,0,1 - 30'000,30'001 - 40'000,40'001 - 50'000,50'001 - 75'000,75'001 - 100'000,100'001 - 200'000,200'001 - 500'000,500'001 - 1'000'000,1'000'001 - u.m./et plus,Total / Totale
0,1.0,Zürich,1,Aeugst am Albis,-,222,73,78,179,139,284,96,12,-,1087
1,1.0,Zürich,2,Affoltern am Albis,-,1540,540,725,1692,982,1126,210,11,-,6829
2,1.0,Zürich,3,Bonstetten,-,541,161,206,568,488,754,188,7,-,2914
3,1.0,Zürich,4,Hausen am Albis,4,429,132,213,440,285,457,117,6,-,2086
4,1.0,Zürich,5,Hedingen,-,402,126,160,425,322,473,135,17,-,2064

In [ ]:
# convert "- to 0
convert_list = taxpayers_df.columns[4:]
convert_list

Index([                         0,               '1 - 30'000',
                '30'001 - 40'000',          '40'001 - 50'000',
                '50'001 - 75'000',         '75'001 - 100'000',
              '100'001 - 200'000',        '200'001 - 500'000',
            '500'001 - 1'000'000', '1'000'001 - u.m./et plus',
                 'Total / Totale'],
      dtype='object')

In [75]:
taxpayers_clean_dash = taxpayers_df.copy()

for col in convert_list:
    taxpayers_clean_dash[col] = pd.to_numeric(taxpayers_clean_dash[col], errors='coerce').fillna(0)

taxpayers_clean_dash

,Kanton ID,Kanton / Canton,Gemeinde ID,Gemeinde / Commune,0,1 - 30'000,30'001 - 40'000,40'001 - 50'000,50'001 - 75'000,75'001 - 100'000,100'001 - 200'000,200'001 - 500'000,500'001 - 1'000'000,1'000'001 - u.m./et plus,Total / Totale
0,1.0,Zürich,1,Aeugst am Albis,0.0,222.0,73.0,78.0,179.0,139.0,284.0,96.0,12.0,0.0,1087
1,1.0,Zürich,2,Affoltern am Albis,0.0,1540.0,540.0,725.0,1692.0,982.0,1126.0,210.0,11.0,0.0,6829
2,1.0,Zürich,3,Bonstetten,0.0,541.0,161.0,206.0,568.0,488.0,754.0,188.0,7.0,0.0,2914
3,1.0,Zürich,4,Hausen am Albis,4.0,429.0,132.0,213.0,440.0,285.0,457.0,117.0,6.0,0.0,2086
4,1.0,Zürich,5,Hedingen,0.0,402.0,126.0,160.0,425.0,322.0,473.0,135.0,17.0,0.0,2064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2170,26.0,Jura,6808,Clos du Doubs,24.0,229.0,81.0,116.0,175.0,82.0,72.0,7.0,0.0,0.0,786
2171,26.0,Jura,6809,Haute-Ajoie,27.0,173.0,80.0,93.0,158.0,77.0,69.0,0.0,0.0,0.0,680
2172,26.0,Jura,6810,La Baroche,31.0,222.0,80.0,91.0,162.0,69.0,62.0,5.0,0.0,0.0,722
2173,26.0,Jura,10000,Total / Totale,2052.0,11974.0,4385.0,5417.0,9722.0,5061.0,5354.0,501.0,33.0,9.0,44508
2174,27.0,Schweiz / Suisse / Svizzera / Svizra,10000,Total / Totale,89494.0,1116206.0,399948.0,512639.0,1116430.0,654116.0,760491.0,132688.0,12535.0,3916.0,4798463

In [76]:
#check before convert
dash_before = (taxpayers_df[convert_list] == "- ").sum().sum()
print(f"number of dash before convert: {dash_before}")

#check after convert
dash_after =  (taxpayers_clean_dash[convert_list] == 0).sum().sum()
print(f"number of dash after convert: {dash_after}")

number of dash before convert: 4602
number of dash after convert: 4602

In [101]:
# Chk duplicate ID 
taxpayers_clean_dash['Gemeinde ID'].duplicated().sum()

np.int64(26)

In [103]:
taxpayers_clean_dash['Gemeinde / Commune'].value_counts()

Gemeinde / Commune
Total / Totale         27
Aeugst am Albis         1
Aadorf                  1
Kradolf-Schönenberg     1
Sulgen                  1
                       ..
Marsens                 1
Jaun                    1
Hauteville              1
Gruyères                1
La Baroche              1
Name: count, Length: 2149, dtype: int64

In [111]:
taxpayers_final = taxpayers_clean_dash[taxpayers_clean_dash['Gemeinde / Commune'] != 'Total / Totale']
taxpayers_final = taxpayers_final.rename(columns={"Total / Totale": "num_taxpayers"})
taxpayers_final['Gemeinde ID'].duplicated().sum()

np.int64(0)

In [112]:
taxpayers_final.head()

,Kanton ID,Kanton / Canton,Gemeinde ID,Gemeinde / Commune,0,1 - 30'000,30'001 - 40'000,40'001 - 50'000,50'001 - 75'000,75'001 - 100'000,100'001 - 200'000,200'001 - 500'000,500'001 - 1'000'000,1'000'001 - u.m./et plus,num_taxpayers
0,1.0,Zürich,1,Aeugst am Albis,0.0,222.0,73.0,78.0,179.0,139.0,284.0,96.0,12.0,0.0,1087
1,1.0,Zürich,2,Affoltern am Albis,0.0,1540.0,540.0,725.0,1692.0,982.0,1126.0,210.0,11.0,0.0,6829
2,1.0,Zürich,3,Bonstetten,0.0,541.0,161.0,206.0,568.0,488.0,754.0,188.0,7.0,0.0,2914
3,1.0,Zürich,4,Hausen am Albis,4.0,429.0,132.0,213.0,440.0,285.0,457.0,117.0,6.0,0.0,2086
4,1.0,Zürich,5,Hedingen,0.0,402.0,126.0,160.0,425.0,322.0,473.0,135.0,17.0,0.0,2064

,Kanton ID,Kanton / Canton,Gemeinde ID,Gemeinde / Commune,0,1 - 30'000,30'001 - 40'000,40'001 - 50'000,50'001 - 75'000,75'001 - 100'000,100'001 - 200'000,200'001 - 500'000,500'001 - 1'000'000,1'000'001 - u.m./et plus,num_taxpayers
0,1.0,Zürich,1,Aeugst am Albis,0.0,222.0,73.0,78.0,179.0,139.0,284.0,96.0,12.0,0.0,1087
1,1.0,Zürich,2,Affoltern am Albis,0.0,1540.0,540.0,725.0,1692.0,982.0,1126.0,210.0,11.0,0.0,6829
2,1.0,Zürich,3,Bonstetten,0.0,541.0,161.0,206.0,568.0,488.0,754.0,188.0,7.0,0.0,2914
3,1.0,Zürich,4,Hausen am Albis,4.0,429.0,132.0,213.0,440.0,285.0,457.0,117.0,6.0,0.0,2086
4,1.0,Zürich,5,Hedingen,0.0,402.0,126.0,160.0,425.0,322.0,473.0,135.0,17.0,0.0,2064

# Sheet 522

In [79]:
# load and skip row
income_df = pd.read_excel(
    excel_file,
    sheet_name="522",
    skiprows=2,
    header=0
)

income_df.head()

,Kanton ID,Kanton / Canton,Gemeinde ID,Gemeinde / Commune,0,1 - 30'000,30'001 - 40'000,40'001 - 50'000,50'001 - 75'000,75'001 - 100'000,100'001 - 200'000,200'001 - 500'000,500'001 - 1'000'000,1'000'001 - u.m./et plus,Total / Totale
0,1.0,Zürich,1,Aeugst am Albis,217324,3225594,3330022,4136030,13092018,13644819,36788871,24176521,7950800,-,110358999
1,NaN,NaN,2,Affoltern am Albis,1416064,28672568,26689741,42744427,121067589,83979374,116006928,48036099,5955601,-,475619991
2,NaN,NaN,3,Bonstetten,-,8692599,8081305,11095957,45731404,47087761,91731834,39683086,3752700,-,258113870
3,NaN,NaN,4,Hausen am Albis,472627,7333511,6774464,11250037,32949344,25297500,56182715,26350887,3928325,-,178368844
4,NaN,NaN,5,Hedingen,432570,6232366,5546994,10573020,31160558,30005530,58666229,33505519,8478800,-,185857586

In [80]:
# Check null
income_df.isna().sum()

Kanton ID                   2122
Kanton / Canton             2122
Gemeinde ID                    0
Gemeinde / Commune             0
0                              0
1 - 30'000                     0
30'001 - 40'000                0
40'001 - 50'000                0
50'001 - 75'000                0
75'001 - 100'000               0
100'001 - 200'000              0
200'001 - 500'000              0
500'001 - 1'000'000            0
1'000'001 - u.m./et plus       0
Total / Totale                 0
dtype: int64

In [81]:
# first fill-forword Kanton ID and Kanton/Canton

income_df["Kanton ID"] = income_df["Kanton ID"].ffill()
income_df["Kanton / Canton"] = income_df["Kanton / Canton"].ffill()

# check null value again
income_df.isna().sum()

Kanton ID                   0
Kanton / Canton             0
Gemeinde ID                 0
Gemeinde / Commune          0
0                           0
1 - 30'000                  0
30'001 - 40'000             0
40'001 - 50'000             0
50'001 - 75'000             0
75'001 - 100'000            0
100'001 - 200'000           0
200'001 - 500'000           0
500'001 - 1'000'000         0
1'000'001 - u.m./et plus    0
Total / Totale              0
dtype: int64

In [82]:
# convert "- to 0
convert_list = income_df.columns[4:]
convert_list

Index([                         0,               '1 - 30'000',
                '30'001 - 40'000',          '40'001 - 50'000',
                '50'001 - 75'000',         '75'001 - 100'000',
              '100'001 - 200'000',        '200'001 - 500'000',
            '500'001 - 1'000'000', '1'000'001 - u.m./et plus',
                 'Total / Totale'],
      dtype='object')

In [95]:
income_clean_dash = income_df.copy()

for col in convert_list:
    income_clean_dash[col] = pd.to_numeric(income_clean_dash[col], errors='coerce').fillna(0)

income_clean_dash

,Kanton ID,Kanton / Canton,Gemeinde ID,Gemeinde / Commune,0,1 - 30'000,30'001 - 40'000,40'001 - 50'000,50'001 - 75'000,75'001 - 100'000,100'001 - 200'000,200'001 - 500'000,500'001 - 1'000'000,1'000'001 - u.m./et plus,Total / Totale
0,1.0,Zürich,1,Aeugst am Albis,2.173240e+05,3.225594e+06,3.330022e+06,4.136030e+06,1.309202e+07,1.364482e+07,3.678887e+07,2.417652e+07,7.950800e+06,0.000000e+00,110358999
1,1.0,Zürich,2,Affoltern am Albis,1.416064e+06,2.867257e+07,2.668974e+07,4.274443e+07,1.210676e+08,8.397937e+07,1.160069e+08,4.803610e+07,5.955601e+06,0.000000e+00,475619991
2,1.0,Zürich,3,Bonstetten,0.000000e+00,8.692599e+06,8.081305e+06,1.109596e+07,4.573140e+07,4.708776e+07,9.173183e+07,3.968309e+07,3.752700e+06,0.000000e+00,258113870
3,1.0,Zürich,4,Hausen am Albis,4.726270e+05,7.333511e+06,6.774464e+06,1.125004e+07,3.294934e+07,2.529750e+07,5.618272e+07,2.635089e+07,3.928325e+06,0.000000e+00,178368844
4,1.0,Zürich,5,Hedingen,4.325700e+05,6.232366e+06,5.546994e+06,1.057302e+07,3.116056e+07,3.000553e+07,5.866623e+07,3.350552e+07,8.478800e+06,0.000000e+00,185857586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2170,26.0,Jura,6808,Clos du Doubs,8.203100e+04,5.069553e+06,4.371827e+06,6.072732e+06,1.296854e+07,4.889848e+06,5.444099e+06,1.301644e+06,0.000000e+00,0.000000e+00,40200279
2171,26.0,Jura,6809,Haute-Ajoie,1.447850e+05,3.952077e+06,3.355958e+06,4.682129e+06,1.085297e+07,6.802872e+06,5.310069e+06,0.000000e+00,0.000000e+00,0.000000e+00,35733362
2172,26.0,Jura,6810,La Baroche,1.292000e+05,4.122656e+06,4.037156e+06,5.528186e+06,1.001356e+07,5.826678e+06,4.838392e+06,0.000000e+00,0.000000e+00,0.000000e+00,35197527
2173,26.0,Jura,10000,Total / Totale,7.789868e+06,2.261388e+08,2.155452e+08,2.889995e+08,6.963352e+08,4.418487e+08,4.483630e+08,1.042498e+08,1.996258e+07,1.628515e+07,2465517712
2174,27.0,Schweiz / Suisse / Svizzera / Svizra,10000,Total / Totale,1.000482e+09,2.017190e+10,1.930793e+10,2.923068e+10,7.979794e+10,5.643131e+10,7.889933e+10,3.081257e+10,7.760374e+09,8.963820e+09,332376344346

In [96]:
#check before convert
dash_before = (income_df[convert_list] == "- ").sum().sum()
print(f"number of dash before convert: {dash_before}")

#check after convert
dash_after =  (income_clean_dash[convert_list] == 0).sum().sum()
print(f"number of dash after convert: {dash_after}")

number of dash before convert: 4351
number of dash after convert: 4351

In [114]:
# Chk duplicate ID 
income_clean_dash['Gemeinde ID'].duplicated().sum()

np.int64(26)

In [115]:
# Chk duplicate ID 
income_clean_dash['Gemeinde / Commune'].duplicated().sum()

np.int64(26)

In [117]:
income_final = income_clean_dash[income_clean_dash['Gemeinde / Commune'] != 'Total / Totale']
income_final = income_final.rename(columns={"Total / Totale": "Total_income"})
income_final['Gemeinde ID'].duplicated().sum()

np.int64(0)

In [118]:
income_final.head()

,Kanton ID,Kanton / Canton,Gemeinde ID,Gemeinde / Commune,0,1 - 30'000,30'001 - 40'000,40'001 - 50'000,50'001 - 75'000,75'001 - 100'000,100'001 - 200'000,200'001 - 500'000,500'001 - 1'000'000,1'000'001 - u.m./et plus,Total_income
0,1.0,Zürich,1,Aeugst am Albis,217324.0,3225594.0,3330022.0,4136030.0,13092018.0,13644819.0,36788871.0,24176521.0,7950800.0,0.0,110358999
1,1.0,Zürich,2,Affoltern am Albis,1416064.0,28672568.0,26689741.0,42744427.0,121067589.0,83979374.0,116006928.0,48036099.0,5955601.0,0.0,475619991
2,1.0,Zürich,3,Bonstetten,0.0,8692599.0,8081305.0,11095957.0,45731404.0,47087761.0,91731834.0,39683086.0,3752700.0,0.0,258113870
3,1.0,Zürich,4,Hausen am Albis,472627.0,7333511.0,6774464.0,11250037.0,32949344.0,25297500.0,56182715.0,26350887.0,3928325.0,0.0,178368844
4,1.0,Zürich,5,Hedingen,432570.0,6232366.0,5546994.0,10573020.0,31160558.0,30005530.0,58666229.0,33505519.0,8478800.0,0.0,185857586

In [125]:
# Export

taxpayers_final.to_csv("data/num_taxpayers_by_gemeinde.csv", index=False)
income_final.to_csv("data/total_income_by_gemeinde.csv", index=False)

print("saved:", len(taxpayers_final), "rows ->", "num_taxpayers_by_gemeinde.csv")
print("saved:", len(income_final), "rows ->", "total_income_by_gemeinde.csv")

saved: 2148 rows -> num_taxpayers_by_gemeinde.csv
saved: 2148 rows -> total_income_by_gemeinde.csv

#### This data is keyed by **`Gemeinde ID` (BFS municipality number)**, not by postal code.
  To join with the supermarket/population data (keyed by postal code), a PLZ↔BFS-Nr
  crosswalk table is needed (found via swisstopo's official locality directory)